### ISSUE TITLE
Deleting a scheduled pipeline blow up Gaia

### ISSUE THREAD

**Issue by Skarlso** [gaia-pipeline/gaia#243]
```
1c46ff233 false [*/1 * * * *] 755daa76-cf06-538d-b6a0-1f441ac4cc24 [golang] false 0xc000588640}"
2020-04-27T20:49:49.488+0200 [DEBUG] plugin.testcron2_golang: 2020/04/27 20:49:49 Cleanup has been finished!
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1601357]

goroutine 25 [running]:
github.com/gaia-pipeline/gaia/workers/scheduler.createPipelineCmd(0x0, 0x44)
	/Users/skarlso/goprojects/gaia-pipeline/gaia/workers/scheduler/create_cmd.go:17 +0x57
github.com/gaia-pipeline/gaia/workers/scheduler.(*Scheduler).prepareAndExec(0xc0000bc660, 0xc0001663c0, 0x24, 0x10, 0x1, 0x0, 0x0, 0x0, 0xc0001935c2, 0x9, ...)
	/Users/skarlso/goprojects/gaia-pipeline/gaia/workers/scheduler/scheduler.go:196 +0x681
github.com/gaia-pipeline/gaia/workers/scheduler.(*Scheduler).work(0xc0000bc660)
	/Users/skarlso/goprojects/gaia-pipeline/gaia/workers/scheduler/scheduler.go:149 +0xe3
created by github.com/gaia-pipeline/gaia/workers/scheduler.(*Scheduler).Init
	/Users/skarlso/goprojects/gaia-pipeline/gaia/workers/scheduler/scheduler.go:118 +0x4c
```

**Comment by Skarlso** [comment]
This is master, not my scheduler change..

**Comment by Skarlso** [comment]
```
" pipeline="&{1 testcron2 0xc0000d4320 golang /Users/skarlso/goprojects/gaia-pipeline/gaia/tmp/pipelines/testcron2_golang [202 22 6 185 174 129 80 19 153 17 250 239 145 227 165 160 178 154 179 86 161 60 237 107 65 138 30 139 184 58 224 168] [0xc000178930 0xc0001789a0 0xc000178a10 0xc000178a80 0xc000178af0 0xc000178b60 0xc000178bd0] 2020-04-27 20:47:53.505596 +0200 CEST 0e68e830-9f54-433e-9895-68a1c46ff233 false [*/1 * * * *] 755daa76-cf06-538d-b6a0-1f441ac4cc24 [golang] false 0xc000588640}"
2020-04-27T20:49:49.271+0200 [ERROR] Gaia: cannot schedule pipeline from periodic schedule: error="fork/exec /Users/skarlso/goprojects/gaia-pipeline/gaia/tmp/pipelines/testcron2_golang: no such file or directory
```

**Comment by Skarlso** [comment]
Okay, this is with the new code: 

```

--- output ---
" pipeline="&{2 testcron 0xc000282000 golang /Users/skarlso/goprojects/gaia-pipeline/gaia/tmp/pipelines/testcron_golang [209 150 251 8 153 93 10 93 137 216 133 203 84 76 6 168 168 184 91 240 164 244 194 60 35 84 181 51 87 0 253 231] [0xc0003d4380 0xc0003d43f0 0xc0003d4460 0xc0003d44d0 0xc0003d4540 0xc0003d45b0 0xc0003d4620] 2020-04-27 20:53:03.814155 +0200 CEST 5017b441-feb9-4d62-bdf3-ebf20aa21c02 false [*/5 * * * *] 1d531f43-171c-5ed8-bdc6-391e609c4cb3 [golang] false 0xc0004346e0}"
2020-04-27T20:54:02.921+0200 [DEBUG] plugin.testcron_golang: 2020/04/27 20:54:02 Cleanup has been finished!
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1601357]

goroutine 25 [running]:
github.com/gaia-pipeline/gaia/workers/scheduler.createPipelineCmd(0x0, 0x43)
	/Users/skarlso/goprojects/gaia-pipeline/gaia/workers/scheduler/create_cmd.go:17 +0x57
github.com/gaia-pipeline/gaia/workers/scheduler.(*Scheduler).prepareAndExec(0xc000146ea0, 0xc000675470, 0x24, 0x5, 0x2, 0x0, 0x0, 0x0, 0xc0003d0bd0, 0x9, ...)
	/Users/skarlso/goprojects/gaia-pipeline/gaia/workers/scheduler/scheduler.go:196 +0x681
github.com/gaia-pipeline/gaia/workers/scheduler.(*Scheduler).work(0xc000146ea0)
	/Users/skarlso/goprojects/gaia-pipeline/gaia/workers/scheduler/scheduler.go:149 +0xe3
created by github.com/gaia-pipeline/gaia/workers/scheduler.(*Scheduler).Init
	/Users/skarlso/goprojects/gaia-pipeline/gaia/workers/scheduler/scheduler.go:118 +0x4c
exit status 2
make: *** [dev] Error 1
```

It seems the crontab parser is wrong? It looks like `*/5 * * * *` is 5 seconds for it instead of 5 minutes. `*/5 * * * *` according to crontab is every 5 minutes... So either the parser is incorrect or we pass in something incorrectly.

**Comment by Skarlso** [comment]
Fixed in my other PR.
